extends SceneTree

## Measures how far each noise source carries from every space in the blockout,
## through the tunnels and in a straight line, and writes the two side by side.
##
## THIS IS THE ANSWER TO OPEN DESIGN QUESTION #5, in numbers rather than in
## principle. core_loop_noise.gd emits a noise event as a plain radius, so the
## creature hears it through solid asteroid; the tunnels are what the sound
## actually has to travel down. Every row where the two columns differ is
## somewhere the shipping prototype thinks the creature can hear you and the
## level says it cannot.
##
## Run headless:
##   godot --headless --path <root> --script res://tools/level_design/report_sound_reach.gd

const DEFAULT_LEVEL_PATH := "res://levels/design/level_asteroid_blockout.tscn"
const OUTPUT_PATTERN := "res://documentation/design/%s_sound_reach.md"

## Metres sampled along a tunnel when measuring straight-line coverage.
const SAMPLE_STEP := 1.0

## The noise sources core_loop_knobs.gd defines, as the radius each carries.
const SOURCES := [
	{"name": "drill / crank", "loudness": 60.0},
	{"name": "sprint", "loudness": 20.0},
	{"name": "thrust", "loudness": 12.0},
]


func _initialize() -> void:
	_run()


func _run() -> void:
	await process_frame

	var packed := load(_level_path()) as PackedScene
	if packed == null:
		printerr("Could not load %s" % _level_path())
		quit(1)
		return
	var level := packed.instantiate() as MineLevel
	root.add_child(level)
	await process_frame

	var graph := level.build_graph()
	var report := _render_report(graph)
	DirAccess.make_dir_recursive_absolute(OUTPUT_PATTERN.get_base_dir())
	var output_path := OUTPUT_PATTERN % _level_path().get_file().get_basename()
	var file := FileAccess.open(output_path, FileAccess.WRITE)
	if file == null:
		printerr("Could not write %s" % output_path)
		quit(1)
		return
	file.store_string(report)
	file.close()

	print("Wrote %s" % output_path)
	print(_render_summary(graph))
	level.free()
	quit(0)


func _render_report(graph: LevelGraph) -> String:
	var lines := PackedStringArray()
	lines.append("# How far noise carries in the mine blockout")
	lines.append("")
	lines.append(
		(
			"Generated by `tools/level_design/report_sound_reach.gd` from `%s`."
			% _level_path().trim_prefix("res://")
		)
	)
	lines.append("")
	lines.append(
		(
			"Loudness is a radius in metres, matching `core_loop_noise.gd`. "
			+ "**Through tunnels** walks the level graph, because sound does not pass "
			+ "through rock. **Straight line** is what the prototype does today. "
			+ "Where the two differ, the creature currently hears through solid asteroid."
		)
	)
	lines.append("")
	lines.append(_render_summary(graph))
	lines.append("")
	lines.append("## Per space, drilling (60 m)")
	lines.append("")
	lines.append("| Noise made in | Spaces reached | | Tunnel metres reached | |")
	lines.append("|---|---|---|---|---|")
	lines.append("| | through tunnels | straight line | through tunnels | straight line |")

	for space: LevelGraph.Space in graph.spaces:
		var measured := _measure(graph, space.id, 60.0)
		(
			lines
			. append(
				(
					"| `%s` | %d | %d | %.0f | %.0f |"
					% [
						space.id,
						measured["graph_spaces"],
						measured["straight_spaces"],
						measured["graph_metres"],
						measured["straight_metres"],
					]
				)
			)
		)
	lines.append("")
	return "\n".join(lines) + "\n"


func _render_summary(graph: LevelGraph) -> String:
	var lines := PackedStringArray()
	lines.append("## Averaged over every space as the origin")
	lines.append("")
	lines.append("| Source | Loudness | Spaces heard | | Tunnel metres heard | | Overstated by |")
	lines.append("|---|---|---|---|---|---|---|")
	lines.append("| | | tunnels | straight | tunnels | straight | |")

	for source: Dictionary in SOURCES:
		var loudness: float = source["loudness"]
		var graph_spaces := 0.0
		var straight_spaces := 0.0
		var graph_metres := 0.0
		var straight_metres := 0.0
		for space: LevelGraph.Space in graph.spaces:
			var measured := _measure(graph, space.id, loudness)
			graph_spaces += measured["graph_spaces"]
			straight_spaces += measured["straight_spaces"]
			graph_metres += measured["graph_metres"]
			straight_metres += measured["straight_metres"]

		var count := float(maxi(graph.spaces.size(), 1))
		var overstatement := 0.0
		if graph_metres > 0.0:
			overstatement = (straight_metres / graph_metres - 1.0) * 100.0
		(
			lines
			. append(
				(
					"| %s | %.0f m | %.1f | %.1f | %.0f | %.0f | %.0f%% more tunnel |"
					% [
						source["name"],
						loudness,
						graph_spaces / count,
						straight_spaces / count,
						graph_metres / count,
						straight_metres / count,
						overstatement,
					]
				)
			)
		)
	return "\n".join(lines)


func _measure(graph: LevelGraph, origin_id: StringName, loudness: float) -> Dictionary:
	var field := graph.propagate_from_space(origin_id, loudness)
	var graph_metres := 0.0
	for tunnel: LevelGraph.Tunnel in graph.tunnels:
		graph_metres += field.covered_length(tunnel.id)

	var origin := graph.find_space(origin_id).position
	return {
		"graph_spaces": field.remaining_at_space.size(),
		"graph_metres": graph_metres,
		"straight_spaces": graph.straight_line_audible_space_ids(origin, loudness).size(),
		"straight_metres": _straight_line_metres(graph, origin, loudness),
	}


func _straight_line_metres(graph: LevelGraph, origin: Vector3, loudness: float) -> float:
	var total := 0.0
	for tunnel: LevelGraph.Tunnel in graph.tunnels:
		var span := tunnel.length()
		var steps := maxi(int(ceil(span / SAMPLE_STEP)), 1)
		var step_length := span / float(steps)
		for index: int in steps:
			if origin.distance_to(tunnel.point_at((float(index) + 0.5) * step_length)) <= loudness:
				total += step_length
	return total


## Which level to read. Defaults to the asteroid blockout; `-- --level=res://...`
## points any of these tools at another one.
func _level_path() -> String:
	for argument: String in OS.get_cmdline_user_args():
		if argument.begins_with("--level="):
			return argument.trim_prefix("--level=")
	return DEFAULT_LEVEL_PATH
