class_name CreatureNavSourceDemoMap
extends Node3D

## An ARBITRARY CONCAVE MESH, with its collision, that changes at runtime.
##
## THIS FILE IS THE OPPOSITE OF `creature_nav_demo_map.gd` ON THE ONE POINT THAT MATTERS.
## That map draws with CSG and collides with generated convex boxes, on purpose, because
## `NavigationProbe.is_solid` is exact for a convex collider and impossible for a concave
## one. This map sets `use_collision = true` and collides with the CSG trimesh itself --
## curved, off-axis, and with no interior for an overlap test to find. It is the shape a
## real level has, and the shape the section 12.1 lattice sweep gets wrong.
##
## What the sweep does here, if you turn `use_flood` off on the source and look at the F1
## overlay: a point deep inside the rock touches no triangle, so `shape_fits` says it fits
## and `clearance_at` returns the ceiling. Section 12.2 sorts by clearance DESCENDING, so
## those rock points are decimated FIRST and evict the real candidates within
## `node_separation` of them. The graph fills the stone.
##
## THE GEOMETRY, AND WHY EACH PIECE IS SHAPED THE WAY IT IS:
##
##     rock          one box, and everything below is subtracted out of it
##     chamber A     sphere, r 8   the spawn; curved walls, so the crawler has to hug one
##     chamber B     sphere, r 9   through a wide bore the alien fits down
##     chamber C     sphere, r 6   through a bore it does not
##     wide bore     r 3.0, DIAGONAL      normal body needs 1.25 m of clearance
##     tight bore    r 0.6, axis-aligned  the alien needs 0.75 m; the player's hull is 0.4
##
## THE TIGHT BORE IS AXIS-ALIGNED AND THE WIDE ONE IS NOT, and that is a real constraint
## rather than laziness. Section 12.1's lattice is snapped to world multiples of
## `candidate_spacing`, and the flood steps between adjacent lattice cells -- so a 1.2 m
## tube running diagonally contains no two consecutive lattice points and the flood cannot
## follow it. At 6 m the wide bore has room for the lattice at any angle. A passage the
## alien is meant to squeeze through has to be built on the lattice; a passage it is meant
## to swim down does not.
##
## CHAMBER C IS THE POINT OF THE TIGHT BORE. The flood crosses it -- 0.6 m of clearance is
## more than the 0.25 m passage probe needs -- so chamber C fills with perfectly good nodes,
## and section 13.2 then refuses every edge across the bore because neither body fits. That
## is Invariant 5 with no flag, marker or special case: section 43's Scenarios C and G, on
## a trimesh. Fly through it yourself to prove the opening is real.
##
## MINING GROWS THE BRUSH LIST FOREVER, AND IT IS NOT FREE. `CSGShape3D` rebuilds the whole
## combiner and re-uploads the entire cave's trimesh to Jolt on every child edit, so a
## hundred mined holes is a hundred-brush rebuild per hole. `MAX_DIGS` caps it. Without the
## cap the scene gets progressively choppier the more you mine, which reads as a navigation
## bug and is nothing of the kind.

## The solid the cave is carved out of. Also the flood's fence -- see `bounds()`.
const ROCK := Vector3(64.0, 28.0, 64.0)
const TERRAIN_LAYER: int = 1

const CHAMBER_A := Vector3(-16.0, 0.0, -12.0)
const CHAMBER_A_RADIUS: float = 8.0
const CHAMBER_B := Vector3(14.0, 2.0, 12.0)
const CHAMBER_B_RADIUS: float = 9.0
const CHAMBER_C := Vector3(16.0, 0.0, -12.0)
const CHAMBER_C_RADIUS: float = 6.0

## Alien-passable. The normal body's envelope is 1.25 m, so a 3 m bore is TUNNEL_SWIM.
const WIDE_BORE: float = 3.0
## Alien-impassable, player-passable. The squeezed body needs 0.75 m and the player's hull
## needs 0.4. Both ends sit on the lattice, at y = 0 and z = -12.
const TIGHT_BORE: float = 0.6
const TUBE_SIDES: int = 16

## Brush cap. See the class docstring on why a demo needs one.
const MAX_DIGS: int = 60

var digs: int = 0

var _cave: CSGCombiner3D = null


## The whole solid, which is also every cubic metre of air the cave can contain. Handed to
## the source as its bake bounds, where it serves as the flood's fence.
static func bounds() -> AABB:
	return AABB(-0.5 * ROCK, ROCK)


## Points the flood starts from, and there is nothing clever about where they come from:
## they are the centres of the brushes that carved the cave, which are open by construction.
##
## CHAMBER C IS DELIBERATELY NOT ONE. Seeding it would fill it whatever the tight bore did,
## and the whole demonstration is that the flood gets there THROUGH a passage the alien
## cannot use.
static func air_seeds() -> PackedVector3Array:
	return PackedVector3Array([CHAMBER_A, CHAMBER_B])


func _ready() -> void:
	var combiner := CSGCombiner3D.new()
	combiner.name = "Terrain"
	# THE WHOLE POINT OF THIS SCENE. A concave trimesh collider, generated by the engine from
	# the same brushes that make the visual, so the two cannot drift.
	combiner.use_collision = true
	combiner.collision_layer = TERRAIN_LAYER
	combiner.collision_mask = 0
	# `material_override`, not `material`: CSGCombiner3D is not a CSGPrimitive3D and has no
	# `material` of its own. Overriding on the root is what gives the whole cave one surface.
	combiner.material_override = _rock_material()
	add_child(combiner)

	var rock := CSGBox3D.new()
	rock.size = ROCK
	rock.operation = CSGShape3D.OPERATION_UNION
	combiner.add_child(rock)

	# Nested, so every carve is one subtraction from the rock rather than a chain of them.
	# Only the ROOT combiner generates collision, which is what makes the whole cave one
	# trimesh instead of one per brush.
	_cave = CSGCombiner3D.new()
	_cave.name = "Cave"
	_cave.operation = CSGShape3D.OPERATION_SUBTRACTION
	combiner.add_child(_cave)

	_cave.add_child(_ball(CHAMBER_A, CHAMBER_A_RADIUS))
	_cave.add_child(_ball(CHAMBER_B, CHAMBER_B_RADIUS))
	_cave.add_child(_ball(CHAMBER_C, CHAMBER_C_RADIUS))
	_cave.add_child(_tube(CHAMBER_A, CHAMBER_B, WIDE_BORE))
	_cave.add_child(_tube(CHAMBER_A, CHAMBER_C, TIGHT_BORE))


## The volume the tight bore occupies, for the per-bake Invariant 5 check.
static func tight_bore_volume() -> AABB:
	var span: Vector3 = CHAMBER_C - CHAMBER_A
	var girth := Vector3(TIGHT_BORE, TIGHT_BORE, TIGHT_BORE)
	# Pulled in by each chamber's radius, so the check measures the BORE and not the open
	# space at either end of it.
	var from: Vector3 = CHAMBER_A + span.normalized() * CHAMBER_A_RADIUS
	var to: Vector3 = CHAMBER_C - span.normalized() * CHAMBER_C_RADIUS
	return AABB(from, Vector3.ZERO).expand(to).grow(girth.x)


## Carves a sphere of open space and returns the region that changed, for
## `NavigationSource.notify_terrain_changed`. Returns a zero AABB once `MAX_DIGS` is spent.
func carve(at: Vector3, radius: float) -> AABB:
	if digs >= MAX_DIGS:
		push_warning("creature_nav_source_demo: brush cap reached; no more mining.")
		return AABB()
	digs += 1
	_cave.add_child(_ball(at, radius))
	var girth := Vector3(radius, radius, radius)
	return AABB(at - girth, girth * 2.0)


func _ball(at: Vector3, radius: float) -> CSGSphere3D:
	var ball := CSGSphere3D.new()
	ball.radius = radius
	ball.radial_segments = TUBE_SIDES
	ball.rings = TUBE_SIDES / 2
	ball.operation = CSGShape3D.OPERATION_UNION
	ball.position = at
	return ball


## A capsule-free tube between two points. CSGCylinder3D runs along its own +Y, so the
## basis is built from the segment rather than from an Euler angle nobody can check.
func _tube(from: Vector3, to: Vector3, radius: float) -> CSGCylinder3D:
	var tube := CSGCylinder3D.new()
	tube.radius = radius
	tube.height = from.distance_to(to)
	tube.sides = TUBE_SIDES
	tube.operation = CSGShape3D.OPERATION_UNION
	var along: Vector3 = (to - from).normalized()
	# Any reference that is not parallel to the segment. UP fails for a vertical shaft.
	var reference: Vector3 = Vector3.RIGHT if absf(along.dot(Vector3.UP)) > 0.9 else Vector3.UP
	var side: Vector3 = reference.cross(along).normalized()
	tube.transform = Transform3D(Basis(side, along, side.cross(along)), from.lerp(to, 0.5))
	return tube


func _rock_material() -> StandardMaterial3D:
	var material := StandardMaterial3D.new()
	material.albedo_color = Color(0.34, 0.32, 0.31)
	material.roughness = 0.95
	# Generated CSG carries no UVs worth speaking of, and triplanar is what keeps a carved
	# sphere from reading as a smear.
	material.uv1_triplanar = true
	material.uv1_scale = Vector3(0.25, 0.25, 0.25)
	return material
